### ISSUE TITLE
ansible.cfg

### ISSUE THREAD

**Issue by ncblx** [leucos/ansible-tuto#104]
Hello. 
i can not locate ansible.cfg

[DEPRECATION WARNING]: State 'installed' is deprecated. Using state 'present' instead.. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting  deprecation_warnings=False in ansible.cfg.

**Comment by leucos** [comment]
This is fixed in the latest version (using ansible 2.5+)

Thanks
