### ISSUE TITLE
Can't upload keys at step 00 with newer ubuntu

### ISSUE THREAD

**Issue by ppoloskov** [leucos/ansible-tuto#107]
I've tried to update this tutorial to latest "bionic-" ubuntu release, and it doesn't work - seems like some ssh/keys related problem. It's not an issue as such, however it might indicate some future problems one may encounter in real life. 
Wouldn't it be nice to update this tutorial to latest Ubuntu?

```
BabyMarvin:ansible-tuto paul$ ansible-playbook -c paramiko -i step-00/hosts step-00/setup.yml --ask-pass --become
SSH password:

PLAY [all] *********************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************

paramiko: The authenticity of host '192.168.33.12' can't be established.
Are you sure you want to continue connecting (yes/no)?
yes
fatal: [192.168.33.12]: UNREACHABLE! => {"changed": false, "msg": "('Bad authentication type', ['publickey']) (allowed_types=['publickey'])", "unreachable": true}

paramiko: The authenticity of host '192.168.33.11' can't be established.
The ssh-ed25519 key fingerprint is b'53c239aee32fee953559f0db5de98db6'.
Are you sure you want to continue connecting (yes/no)?
fatal: [192.168.33.10]: UNREACHABLE! => {"changed": false, "msg": "host key mismatch for 192.168.33.10", "unreachable": true}
yes
fatal: [192.168.33.11]: UNREACHABLE! => {"changed": false, "msg": "('Bad authentication type', ['publickey']) (allowed_types=['publickey'])", "unreachable": true}

PLAY RECAP *********************************************************************************************************************************************************
192.168.33.10              : ok=0    changed=0    unreachable=1    failed=0
192.168.33.11              : ok=0    changed=0    unreachable=1    failed=0
192.168.33.12              : ok=0    changed=0    unreachable=1    failed=0
```

**Comment by leucos** [comment]
Thanks for the report.
Concerning `192.168.33.10`, it is because you already have a host key in known_hosts for a different host.
You can get rid of it with `ssh-keygen -R 192.168.33.10`.

However this won't solve the other problem.

I will look into this and make things more easy.

**Comment by ppoloskov** [comment]
Yes, I know about .10 - I did some experiments around it and forget to remove the line from the list of  known hosts. I used ansible ping command as well with the same result - it can't connect to the hosts, neither root no vagrant, but I still can connect using vagrant ssh command or by specifying the private key manually (taken from Vagrant ssh command output). So, it's clearly problem with keys.
I used 'ubuntu/bionic64' official Vagrant box, Mac OS X Mojave, ansible 2.7.1, Vagrant 2.2.0.

**Comment by leucos** [comment]
Yes it is. I have a solution working. I have to iron things out and will push something asap.
The other issue in bionic is that python is not installed in the box by default :)

**Comment by leucos** [comment]
@ppoloskov can you please confirm you have 3 private keys located in `.vagrant/machines/host[0-3]/virtualbox/private_key` after a Vagrant up ?

**Comment by leucos** [comment]
Let me know how it goes (`vagrant destroy -f` required)

**Comment by leucos** [comment]
(also: you only have to run `ansible-playbook -i step-00/hosts step-00/setup.yml` now)

**Comment by ppoloskov** [comment]
Wow, it was fast! Looks like it's fixed, thank you
