### ISSUE TITLE
step 06 (and probably other steps) are mis-formatted

### ISSUE THREAD

**Issue by mgrant0** [leucos/ansible-tuto#71]
...
    - name: Deactivates the default ssl virtualhost
      command: a2dissite default-ssl

    notify:
        - restart apache
...

should be:

    - name: Deactivates the default ssl virtualhost
      command: a2dissite default-ssl
      notify:
        - restart apache

**Comment by leucos** [comment]
Thanks @mgrant0 . You were right, I spotted another instance in step-07 too.
