### ISSUE TITLE
Question: Overview on starting the tutorial

### ISSUE THREAD

**Issue by dgleba** [leucos/ansible-tuto#79]
Stupid noob question, sorry.

Do I install ansible in another linux host, say it's called - David?

Then the tutorial will operate against the three hosts in the vagrant file host0 host1 host2?

Note:
Windows...
I think want to use a vagrant ubuntu machine for ansible called David running on Windows, and run the three vagrant hosts from step-00 for the tutorial to operate on.

**Comment by leucos** [comment]
Well, you could run the tutorial from david VM and start the 3 other VMs from windows, that should be possible.
You might have to fiddle a bit with Vagrant networking in the process.

You could also activate VTx in tour david VM and run the 3 VMs inside the VM. Not ideal, but should work.
Good luck.
