### ISSUE TITLE
Use Ansible 2.x syntax everywhere

### ISSUE THREAD

**Issue by bernardoVale** [leucos/ansible-tuto#85]
Hello @leucos. I was wondering if we can go ahead and assume that new users would be using Ansible 2. If so, we should modify some files to use Ansible new variables such as `become`, `become_user`,  `ansible_user`, `ansible_port` and much more, what do you think about this?

**Comment by leucos** [comment]
Makes sense @bernardoVale . I think it is safe to assume this, since our playbooks are quite simple.

**Comment by bernardoVale** [comment]
Ok @leucos check pull request #86, I've already changed everything. It was pretty simple though.

**Comment by leucos** [comment]
Merged, thanks
