### ISSUE TITLE
sshpass on AWS Centos

### ISSUE THREAD

**Issue by nickopris** [leucos/ansible-tuto#88]
I just followed the documentation  (http://docs.ansible.com/ansible/intro_installation.html) and I'm getting this error:

error: Failed dependencies:
	sshpass is needed by ansible-2.2.0-0.git201605061649.fca5ba1.devel.amzn1.noarch

when running
       sudo rpm -Uvh ./rpm-build/ansible-*.noarch.rpm

I found another thread with this issue which is closed so I am not sure if I am experiencing this because something is misconfigured or I really need to install sshpass.

**Comment by leucos** [comment]
Hi @nickopris . Since this tutorial is not intended to be run on ansible 2.x nor AWS nor centos/rh, I guess you're mistaken. The Ansible github repos is at https://github.com/ansible/ansible.
You'd better ask on IRC or the mailing list though if you're looking for help with Ansible.
Cheers.

**Comment by DineshSobi** [comment]
Enable sshpass

# yum-config-manager --enable epel

#yum install sshpass

Now run ansible install command
