### ISSUE TITLE
Request to port your tutorial to Gitbook

### ISSUE THREAD

**Issue by tumregels** [leucos/ansible-tuto#89]
Good morning!

I would like to port your book/tutorial to [gitbook](www.gitbook.com)
It would be very easy to do it because of markdown.

Can do it if you don't mind.

Also couldn't find the License.

Here is an example of my previous project
[network-programming-with-go-golang](https://www.gitbook.com/book/jannewmarch/network-programming-with-go-golang-/details)

**Comment by leucos** [comment]
Hey @tumregels 

Sure, go ahead, that's great !
About the licence I'd say something BSD like, or even WTFPL ;)

network-programming-with-go-golang looks neat, pinned !

Thanks !

**Comment by tumregels** [comment]
Thanks @leucos for the positive response.

Gitbook will make your book even more famous.

Great, so will proceed accordingly.

Just a small request. If you ever find time please add the license.

**Comment by leucos** [comment]
Fixes in 6dc41bb632f4ed9b52fa7fac4bf99602c588dc93
