### ISSUE TITLE
Role skeleton

### ISSUE THREAD

**Issue by daviderestivo** [leucos/ansible-tuto#95]
Hi Michel,

thanks so much for the nice tutorial. I found it very useful. Since, as far as I can see you're very open to let other people helping you in improving it I would like to suggest a change in chapter 12. Instead of creating the role skeleton via

> mkdir -p step-12/roles/haproxy/{tasks,handlers,templates}
> cp step-11/templates/haproxy.cfg.j2 step-12/roles/haproxy/templates/

It's better to do it using ansible-galaxy: 

> $ ansible-galaxy --offline init simple-role
> \- simple-role was created successfully
> $ ls
> simple-role
> $ ls -alR simple-role/
> total 16
> drwxr-xr-x  12 gutter  staff   408 Nov  8 10:16 .
> drwxr-xr-x   3 gutter  staff   102 Nov  8 10:16 ..
> -rw-r--r--   1 gutter  staff   539 Nov  8 10:16 .travis.yml
> -rw-r--r--   1 gutter  staff  1328 Nov  8 10:16 README.md
> drwxr-xr-x   3 gutter  staff   102 Nov  8 10:16 defaults
> drwxr-xr-x   2 gutter  staff    68 Nov  8 10:16 files
> drwxr-xr-x   3 gutter  staff   102 Nov  8 10:16 handlers
> drwxr-xr-x   3 gutter  staff   102 Nov  8 10:16 meta
> drwxr-xr-x   3 gutter  staff   102 Nov  8 10:16 tasks
> drwxr-xr-x   2 gutter  staff    68 Nov  8 10:16 templates
> drwxr-xr-x   4 gutter  staff   136 Nov  8 10:16 tests
> drwxr-xr-x   3 gutter  staff   102 Nov  8 10:16 vars
> 
> simple-role//defaults:
> total 8
> drwxr-xr-x   3 gutter  staff  102 Nov  8 10:16 .
> drwxr-xr-x  12 gutter  staff  408 Nov  8 10:16 ..
> -rw-r--r--   1 gutter  staff   36 Nov  8 10:16 main.yml
> 
> simple-role//files:
> total 0
> drwxr-xr-x   2 gutter  staff   68 Nov  8 10:16 .
> drwxr-xr-x  12 gutter  staff  408 Nov  8 10:16 ..
> 
> simple-role//handlers:
> total 8
> drwxr-xr-x   3 gutter  staff  102 Nov  8 10:16 .
> drwxr-xr-x  12 gutter  staff  408 Nov  8 10:16 ..
> -rw-r--r--   1 gutter  staff   36 Nov  8 10:16 main.yml
> 
> simple-role//meta:
> total 8
> drwxr-xr-x   3 gutter  staff   102 Nov  8 10:16 .
> drwxr-xr-x  12 gutter  staff   408 Nov  8 10:16 ..
> -rw-r--r--   1 gutter  staff  1604 Nov  8 10:16 main.yml
> 
> simple-role//tasks:
> total 8
> drwxr-xr-x   3 gutter  staff  102 Nov  8 10:16 .
> drwxr-xr-x  12 gutter  staff  408 Nov  8 10:16 ..
> -rw-r--r--   1 gutter  staff   33 Nov  8 10:16 main.yml
> 
> simple-role//templates:
> total 0
> drwxr-xr-x   2 gutter  staff   68 Nov  8 10:16 .
> drwxr-xr-x  12 gutter  staff  408 Nov  8 10:16 ..
> 
> simple-role//tests:
> total 16
> drwxr-xr-x   4 gutter  staff  136 Nov  8 10:16 .
> drwxr-xr-x  12 gutter  staff  408 Nov  8 10:16 ..
> -rw-r--r--   1 gutter  staff    9 Nov  8 10:16 inventory
> -rw-r--r--   1 gutter  staff   69 Nov  8 10:16 test.yml
> 
> simple-role//vars:
> total 8
> drwxr-xr-x   3 gutter  staff  102 Nov  8 10:16 .
> drwxr-xr-x  12 gutter  staff  408 Nov  8 10:16 ..
> -rw-r--r--   1 gutter  staff   32 Nov  8 10:16 main.yml

Regards,
Davide

**Comment by leucos** [comment]
Oh sorry @daviderestivo I didn't see this issue :(
Interesting, why not, we can add both approaches as alternatives !

**Comment by daviderestivo** [comment]
Hi Michel,

sure ... both approaches as alternatives seems a good idea.

Regards,
Davide

**Comment by daviderestivo** [comment]
Hi Michel,

shall I do a pull request?

Regards,
Davide

**Comment by leucos** [comment]
Yes sure ! Thank you.

**Comment by daviderestivo** [comment]
Done. Please have a look to https://github.com/leucos/ansible-tuto/pull/99. Thanks

**Comment by daviderestivo** [comment]
Thanks to your for the time spent in writing this great tutorial.
